// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmhZ9gAmcwHdDzye6du5gDiBGW6M7sFU',
    appId: '1:840282964839:web:598c5ee5f13086a09965c2',
    messagingSenderId: '840282964839',
    projectId: 'flutterfinal-b0c88',
    authDomain: 'flutterfinal-b0c88.firebaseapp.com',
    storageBucket: 'flutterfinal-b0c88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5O3F8ktPvgZS9xtl-_thiwrCfX6dTj-o',
    appId: '1:840282964839:android:5beb877b41d4555e9965c2',
    messagingSenderId: '840282964839',
    projectId: 'flutterfinal-b0c88',
    storageBucket: 'flutterfinal-b0c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgoc5Z2olSJ4BH3fWa3i5S7XX6-FnBnz0',
    appId: '1:840282964839:ios:ae0bbf2148c1e56d9965c2',
    messagingSenderId: '840282964839',
    projectId: 'flutterfinal-b0c88',
    storageBucket: 'flutterfinal-b0c88.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgoc5Z2olSJ4BH3fWa3i5S7XX6-FnBnz0',
    appId: '1:840282964839:ios:ae0bbf2148c1e56d9965c2',
    messagingSenderId: '840282964839',
    projectId: 'flutterfinal-b0c88',
    storageBucket: 'flutterfinal-b0c88.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEmhZ9gAmcwHdDzye6du5gDiBGW6M7sFU',
    appId: '1:840282964839:web:923870af8f91fe7f9965c2',
    messagingSenderId: '840282964839',
    projectId: 'flutterfinal-b0c88',
    authDomain: 'flutterfinal-b0c88.firebaseapp.com',
    storageBucket: 'flutterfinal-b0c88.firebasestorage.app',
  );
}
